#!/bin/bash -e

TEST_DIR=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
TEMP_DIR=$TEST_DIR/tmp
export LOGFILE=$TEMP_DIR/sssd.log

rm -rf $TEMP_DIR
mkdir -p $TEMP_DIR

PAYLOAD="ad ldap://ldap.mydomain.org rfc2307bis dc=eample,dc=com your.ad.example.com - your.kdc.example.com EXAMPLE.COM"

. $TEST_DIR/../sssd-setup
config=$(echo "$(get-sssd-conf $PAYLOAD)")
hash=$(echo "$config" | md5)
if [[ "6dd0800ea3f8127c3b89fe9c4b7c2e9a" != $hash ]]; then
    echo "Generated source is invalid: $hash"
    echo "$config"
    exit 1
fi

save-configuration $TEMP_DIR "config"
if [[ ! -f $TEMP_DIR/sssd.conf ]] || [[ "config" != "$(cat $TEMP_DIR/sssd.conf)" ]]; then
    echo "Missing or wrong configuration file"
    exit 1
fi