#!/bin/bash

TEST_DIR=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
TEMP_DIR=$TEST_DIR/tmp
export LOGFILE=$TEMP_DIR/sssd.log

rm -rf $TEMP_DIR
mkdir -p $TEMP_DIR

PAYLOAD="ad ldap://ldap.mydomain.org rfc2307bis dc=eample,dc=com your.kdc.example.com EXAMPLE.COM"

. $TEST_DIR/../sssd-setup
config=$(echo "$(get-sssd-conf $PAYLOAD)")
hash=$(echo "$config" | md5)
if [[ "b22b6023891807b416d5baaceda280c1" != $hash ]]; then
    echo "Generated source is invalid: $hash"
    echo "$config"
    exit 1
fi

save-configuration $TEMP_DIR "config"
if [[ ! -f $TEMP_DIR/sssd.conf ]] || [[ "config" != "$(cat $TEMP_DIR/sssd.conf)" ]]; then
    echo "Missing or wrong configuration file"
    exit 1
fi

ssh-keygen -t rsa -N "" -f $TEMP_DIR/id_rsa
cp $TEMP_DIR/id_rsa.pub $TEMP_DIR/authorized_keys
docker run --name sssd-test-ldap -e "SLAPD_PASSWORD=passwd" -d sequenceiq/docker-ldap:1.0
docker run --name sssd-test-centos --link sssd-test-ldap:ldap -e "PAYLOAD=ldap ldap://ldap rfc2307 dc=nodomain" -v $TEMP_DIR:/etc/skel/.ssh -dit centos
docker exec sssd-test-centos bash -c "yum update -y && yum install -y git && git clone https://github.com/sequenceiq/consul-plugins-sssd.git && cd consul-plugins-sssd && ./sssd-setup"
docker exec sssd-test-centos bash -c "mkdir /home/binduser && cp -r /etc/skel/.ssh /home/binduser && chown -R binduser:bindgroup /home/binduser"
IP=$(docker inspect -f "{{.NetworkSettings.IPAddress}}" sssd-test-centos)
docker run -ti -v $TEMP_DIR:/root/.ssh trsouz/ssh binduser@$IP -p 2022 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "touch ok"
if [[ 0 -ne $? ]]; then
    echo "Something went wrong during integration test, containers are available"
    exit 1
else
    docker rm -f sssd-test-centos sssd-test-ldap
fi